import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row w-full h-full">
          <div className="flex flex-col w-1/12 md:w-3/12 h-full p-3 gap-4 bg-white">
            <span className="flex flex-row justify-center text-3xl">Ag Sistemas</span>
            <div className="flex flex-col gap-2 pt-2">
              <Link href={'/membro'}
                className="flex flex-row w-full justify-center gap-2 bg-blue-800 hover:bg-blue-900 text-white font-medium py-2 px-4 rounded cursor-pointer">
                  Membros
              </Link>
            </div>
          </div>
          <div className="w-full ">
            <div className="bg-gray-200 px-10 py-2 pb-6 h-screen overflow-y-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
